name: foodapp
description: "A recipe app with categorized recipes and detailed steps."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_svg: ^2.0.5
  lottie: ^2.2.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  
  
  assets:
    - assets/recipes.json
    - assets/images/background.png
    - assets/animations/animation.json
